# Generated by Django 4.2.3 on 2023-08-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='changed',
            new_name='updated',
        ),
    ]
