# Generated by Django 4.2.3 on 2023-08-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_changed_product_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chategory',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'chategories'},
        ),
    ]
